global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django_app'
    static_configs:
      - targets: ['web:8000', 'web1:8001', 'web2:8002']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
